name: Check Dependency Versions

on:
  schedule:
    - cron:  '0 8 1 * *'

jobs:
  build:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Check Dependency Versions
        run: ./gradlew dependencyUpdates
